import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "Is QRYards free to use?",
    answer: "Yes! QRYards is completely free. You can create unlimited QR codes, customize them, and download in PNG or SVG format — all at no cost.",
  },
  {
    question: "What types of QR codes can I create?",
    answer: "QRYards supports 20+ QR code types including URLs, text, email, SMS, WhatsApp, Wi-Fi, vCards, events, social media profiles, coupons, menus, and many more.",
  },
  {
    question: "Can I add my logo to the QR code?",
    answer: "Yes! You can upload your own logo and it will be placed in the center of your QR code. The error correction level automatically adjusts to ensure the code remains scannable.",
  },
  {
    question: "What download formats are available?",
    answer: "You can download your QR codes as PNG (great for digital use) or SVG (perfect for print at any size). Both formats maintain full quality.",
  },
  {
    question: "Do I need to create an account?",
    answer: "No account is required! QRYards works entirely in your browser. Your data never leaves your device — we prioritize your privacy.",
  },
  {
    question: "Will the QR codes work on all devices?",
    answer: "Absolutely. QR codes generated by QRYards follow standard formats and are compatible with all QR code readers on any smartphone or tablet.",
  },
];

const FAQSection = () => {
  return (
    <section id="faq" className="py-20 bg-secondary/50">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Got questions? We&apos;ve got answers
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto"
        >
          <Accordion type="single" collapsible className="space-y-3">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="border rounded-xl px-6 bg-card"
              >
                <AccordionTrigger className="text-left font-medium hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
};

export default FAQSection;